tab = int(input('\ndigite a tabuada que deseja: '))

print(f'\n{'='*5}TABUADA{'='*5}')
print('{} x 01 = {}'.format(tab, tab*1))
print('{} x 02 = {}'.format(tab, tab*2))
print('{} x 03 = {}'.format(tab, tab*3))
print('{} x 04 = {}'.format(tab, tab*4))
print('{} x 05 = {}'.format(tab, tab*5))
print('{} x 06 = {}'.format(tab, tab*6))
print('{} x 07 = {}'.format(tab, tab*7))
print('{} x 08 = {}'.format(tab, tab*8))
print('{} x 09 = {}'.format(tab, tab*9))
print('{} x 10 = {}'.format(tab, tab*10))
print(f'\n{'='*17}\n')